#!bin/sh

CC =gcc

ifeq ($(DEBUG),0)
	CFLAGS		+= -O2
else
	CFLAGS		+= -O0 -g
endif


BIN = shmwrite

SRCS = write.c
SRCS += shm_mem.c
OBJS = write.o
OBJS += shm_mem.o

$(BIN):$(OBJS)
	   $(CC) $(CFLAGS) -o $@ $^ 


clean:
	rm -rf $(BIN)
	rm -rf *.o *.d	   

.PHONY: clean
